In [1]:
import tabula
import pandas as pd

arquivo_pdf = "data.pdf"
pagina = 1  # número da página que contém a tabela
df = tabula.read_pdf(arquivo_pdf, pages=pagina)[0]
df

,Opção,Descrição,Custo do investimento (R$),Retorno esperado (R$),Risco do i
0,1,Ampliação da capacidade do armazém ZDP em 5%,470. 000,410.0,Baixo
1,2,Ampliação da capacidade do armazém MGL em 7%,400.000,330.0,Baixo
2,3,Compra de empilhadeira,170.000,140.0,Médio
3,4,Projeto de P&D I,270.000,250.0,Médio
4,5,Projeto de P&D II,340.000,320.0,Médio
5,6,Aquisição de novos equipamentos,230.000,320.0,Médio
6,7,Capacitação de funcionários,50.000,90.0,Médio
7,8,Ampliação da estrutura de carga rodoviária,440.000,190.0,Alto
8,9,Construção de datacenter,320.000,120.0,Alto
9,10,Aquisição de empresa concorrente,800.000,450.0,Alto
10,11,Compra de serviços em nuvem,120.000,80.0,Baixo
11,12,Criação de aplicativo mobile e desktop,150.000,120.0,Baixo
12,13,Terceirizar serviço de otimização da logística,300.000,380.0,Médio